# Generated by Django 4.1.6 on 2023-02-10 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0005_alter_game_datetime_alter_mot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 18, 38, 47, 623063)),
        ),
    ]
