# Generated by Django 4.1.6 on 2023-02-10 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0007_alter_mot_options_alter_game_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mot',
            options={},
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 18, 58, 30, 483017)),
        ),
    ]
