# Generated by Django 4.1.6 on 2023-02-10 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0010_rename_is_finished_game_is_win_game_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 23, 59, 26, 701720)),
        ),
    ]
