# Generated by Django 4.1.6 on 2023-02-10 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0011_alter_game_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_win',
        ),
        migrations.RemoveField(
            model_name='game',
            name='points',
        ),
        migrations.AddField(
            model_name='game',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 0, 0, 19, 657236)),
        ),
    ]
