# Generated by Django 4.1.6 on 2023-02-10 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0012_remove_game_is_win_remove_game_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='is_finished',
            new_name='is_win',
        ),
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 0, 1, 9, 298405)),
        ),
    ]
