# Generated by Django 4.1.6 on 2023-02-11 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0014_alter_game_datetime_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 1, 52, 35, 579639)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='total_points',
            field=models.IntegerField(),
        ),
    ]
