# Generated by Django 4.1.6 on 2023-02-11 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0017_alter_game_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 2, 16, 44, 275063)),
        ),
    ]
