# Generated by Django 4.1.6 on 2023-02-11 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutomGame', '0020_alter_game_datetime_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 11, 12, 6, 31, 120159)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to='avatars'),
        ),
    ]
